[pytest]
addopts = --alluredir=allure-results
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
log_cli = true
log_cli_level = INFO

# Increase default timeout for performance_glitch_user scenarios
timeout = 60